###
GET http://localhost:8080/books HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/books/6328e641e21e9677dd6f25b8 HTTP/1.1
content-type: application/json

###
POST http://localhost:8080/books HTTP/1.1
content-type: application/json

{
  "name": "Herr der Diebe",
  "author": "Cornelia Funke"
}

###
PATCH http://localhost:8080/books/63288acc0c7dfc4a31d74579 HTTP/1.1
content-type: application/json

{
  "name": "Harry Potter",
  "author": "Joanne Katherine Rowland"
}

###
DELETE http://localhost:8080/books/6328ddad3f31fbac89efa3e3 HTTP/1.1
content-type: application/json
